name: WizCLI Docker Image Scan

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  wlicli-image-scan:
    runs-on: ubuntu-latest
    
    steps:
      # 1. Checkout du code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Build image Docker
      - name: Build Docker image
        run: cd . && docker build . -t app:${{ github.sha }}

      # 3. Wiz Cli image & dir scan
      - name: Download Wiz CLI
        run: curl -o wizcli https://downloads.wiz.io/v1/wizcli/latest/wizcli-linux-amd64 && chmod +x wizcli

      - name: Run wiz-cli docker image scan
        run: ./wizcli scan container-image app:${{ github.sha }} --policies "Marc vulnerabilities policy","Marc secrets policy" --client-id ${{ secrets.WIZ_CLIENT_ID }} --client-secret ${{ secrets.WIZ_CLIENT_SECRET }}
